### ISSUE TITLE
Mechaphlowers is not working on google.colab

### ISSUE THREAD

**Issue by adriengoeller** [phlowers/mechaphlowers#59]
### Describe the current behavior

Colab is currently working in numpy <2.0. It is impossible to upgrade or uninstall numpy because of the preinstalled machine learning packages in colab.

The error seems not very difficult: usage of np.asinh which was not existing in 1.26.

This problem asks a more general question about compatibility with numpy 1: mechaphlowers is designed in numpy 2. But we could make slight changes for compatibility.

### Describe the expected behavior

Replace with np.arcsinh compatible / check for other issue / ci for numpy 1 ?

### Describe the steps

On colab

```python
import numpy as np
print(np.__version__)
np.arcsinh(np.array([np.e, 10.0]))
np.asinh(np.array([np.e, 10.0]))
```
```
1.26.4
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-20-0dc125771cd3>](https://localhost:8080/#) in <cell line: 0>()
      2 print(np.__version__)
      3 np.arcsinh(np.array([np.e, 10.0]))
----> 4 np.asinh(np.array([np.e, 10.0]))

[/usr/local/lib/python3.11/dist-packages/numpy/__init__.py](https://localhost:8080/#) in __getattr__(attr)
    331             import numpy.fft as fft
    332             return fft
--> 333         elif attr == "dtypes":
    334             import numpy.dtypes as dtypes
    335             return dtypes

AttributeError: module 'numpy' has no attribute 'asinh'
```

### Environment

colab

**Comment by adriengoeller** [comment]
solved with release 0.2.0
